version: "3"

services:
    dog-walker-front:
        build: .
        image: moriorgames/dog-walker-front
        restart: unless-stopped
        container_name: dog_walker_front
        ports:
        - "8080:80"
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        tty: true

networks:
    default:
        external:
            name: dev
